
package wsPackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankPolicyService", targetNamespace = "http://webservice.nju.edu.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankPolicyService {


    /**
     * 
     * @param id
     * @return
     *     returns wsPackage.InRegulation
     */
    @WebMethod(operationName = "inRegulation_getById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inRegulation_getById", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.InRegulationGetById")
    @ResponseWrapper(localName = "inRegulation_getByIdResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.InRegulationGetByIdResponse")
    public InRegulation inRegulationGetById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @return
     *     returns java.util.List<wsPackage.InRegulation>
     */
    @WebMethod(operationName = "inRegulation_list")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inRegulation_list", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.InRegulationList")
    @ResponseWrapper(localName = "inRegulation_listResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.InRegulationListResponse")
    public List<InRegulation> inRegulationList();

    /**
     * 
     * @param exRegulation
     * @return
     *     returns int
     */
    @WebMethod(operationName = "exRegulation_count")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exRegulation_count", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.ExRegulationCount")
    @ResponseWrapper(localName = "exRegulation_countResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.ExRegulationCountResponse")
    public int exRegulationCount(
        @WebParam(name = "exRegulation", targetNamespace = "")
        ExRegulation exRegulation);

    /**
     * 
     * @param inRegulation
     * @return
     *     returns int
     */
    @WebMethod(operationName = "inRegulation_count")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inRegulation_count", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.InRegulationCount")
    @ResponseWrapper(localName = "inRegulation_countResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.InRegulationCountResponse")
    public int inRegulationCount(
        @WebParam(name = "inRegulation", targetNamespace = "")
        InRegulation inRegulation);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.HelloResponse")
    public String hello();

    /**
     * 
     * @param id
     * @return
     *     returns wsPackage.ExRegulation
     */
    @WebMethod(operationName = "exRegulation_getById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exRegulation_getById", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.ExRegulationGetById")
    @ResponseWrapper(localName = "exRegulation_getByIdResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.ExRegulationGetByIdResponse")
    public ExRegulation exRegulationGetById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @return
     *     returns java.util.List<wsPackage.ExRegulation>
     */
    @WebMethod(operationName = "exRegulation_list")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exRegulation_list", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.ExRegulationList")
    @ResponseWrapper(localName = "exRegulation_listResponse", targetNamespace = "http://webservice.nju.edu.cn", className = "wsPackage.ExRegulationListResponse")
    public List<ExRegulation> exRegulationList();

}
